# cd, ECS에 배포하기

name: CD Workflow

#CI가 완료되면 일단 dev에서만 ECS에 배포되게끔 구현
on:
  workflow_run:
    workflows: ["CI Workflow"]
    types: [completed]
    branches: [dev]

# 환경변수 정의 : aws 지역, ECS의 url, ECS 클러스터 이름, ECS 서비스 이름, ECS 태스크 정의 이름, ECS 태스크 정의 - > 컨테이너 이름
env:
  AWS_REGION: ap-northeast-2
  IMAGE: public.ecr.aws/w7n1o6b8/monew
  ECS_CLUSTER: cluster-monew
  ECS_SERVICE: monew-task-service-13fqphcy
  ECS_TASK_FAMILY: monew-task
  CONTAINER_NAME: monew-app # ECS 태스크 정의 -> 컨테이너 이름


jobs:
  desploy:
    # CD workflows가 workflow_run에 의해 호출되고 CI가 성공일경우에만 배포
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: AWS ECS Configure(AWS 인증)
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        # ECS 태스크 정의 파일 만들기(컨테이너의 이미지 활용)
        - name: Task Definition file Rendering
          id: render
          uses: aws-actions/amazon-ecs-render-task-definition@v1
          with:
            task-definition: ecs/taskdef-base.json
            container-name: monew-app
            image: public.ecr.aws/w7n1o6b8/monew:latest

        # 새롭게 만든 ECS 태스크 정의를 등록하기, ECS에 새 태스크 정의 적용
        - name: ECS Deploy
          uses: aws-actions/amazon-ecs-deploy-task-definition@v2
          with:
            task-definition: ecs/taskdef-base.json # 위의 render 참조
            service: monew-task-service-ldy1dnpu
            cluster: cluster-monew
            wait-for-service-stability: true # 새로운 서비스가 안정화 될 때까지 기다림
