# ci, Pull Request에서 테스트 및 커버리지

name: CI Workflow

on:
  pull_request:
    branches: [dev, main] # dev, main 브랜치에 pull request 될 때 실행됨
    paths-ignore: ["README.md", "**/*.md"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # PR 코멘트에 커버리지 요약 남기기
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Grant execute permission for gradlew # github Actions에서 gradlew 권한 주기
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests without coverage
        run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification --no-daemon

      - name: Upload coverage report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

# 커버리지 수치를 jacoco XML에서 뽑은 다음 PR 코멘트로 남기기
      - name: Install xmllint (parsing XML) # xmllint 설치하기
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

# 커버리지 코멘트 설계
      - name: Extract coverage numbers
        id: coverage
        run: |
          XML="build/reports/jacoco/test/jacocoTestReport.xml"
          COVERED=$(xmllint --xpath "string(//counter[@type='LINE']/@covered)" "$XML" 2>/dev/null || echo 0)
          MISSED=$(xmllint --xpath "string(//counter[@type='LINE']/@missed)" "$XML" 2>/dev/null || echo 0)
          TOTAL=$((COVERED + MISSED))
          PCT=$(awk "BEGIN { if ($TOTAL==0) print 0; else printf \"%.2f\", ($COVERED/$TOTAL)*100 }")
          echo "covered=$COVERED" >> $GITHUB_OUTPUT
          echo "missed=$MISSED" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "pct=$PCT" >> $GITHUB_OUTPUT

# 커버리지 PR 남기기
      - name: Post coverage comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: jacoco-coverage
          message: |
            ## JaCoCo Coverage Report(자코코 커버리지 리포트!)
            - **CoverageLine(커버리지_라인)** ${{ steps.coverage.outputs.pct }}% (${{ steps.coverage.outputs.covered }} / ${{ steps.coverage.outputs.total }})
            - **Missed(커버리지_수치)** ${{ steps.coverage.outputs.missed }}
            - [HTML 리포트](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) (Artifact) 확인하기